"""Protocol interfaces for service dependencies.

Services depend on these protocols, not concrete adapter implementations.
This keeps the dependency direction clean: adapters implement protocols,
services consume them.
"""

from __future__ import annotations

import ssl
from typing import Any, Protocol


class HttpAdapter(Protocol):
    """Protocol for HTTP operations against the RomM API."""

    def request(self, path: str) -> Any: ...
    def download(self, path: str, dest: str, progress_callback: Any = None) -> None: ...
    def json_request(self, path: str, data: Any, method: str = "POST") -> Any: ...
    def post_json(self, path: str, data: Any) -> Any: ...
    def put_json(self, path: str, data: Any) -> Any: ...
    def upload_multipart(self, path: str, file_path: str, method: str = "POST") -> Any: ...
    def with_retry(self, fn: Any, *args: Any, max_attempts: int = 3, base_delay: int = 1, **kwargs: Any) -> Any: ...

    @staticmethod
    def is_retryable(exc: Exception) -> bool: ...

    def resolve_system(self, platform_slug: str, platform_fs_slug: str | None = None) -> str: ...
    def load_platform_map(self) -> dict: ...
    def ssl_context(self) -> ssl.SSLContext: ...
    def auth_header(self) -> str: ...
    def translate_http_error(self, exc: Exception, url: str, method: str = "GET") -> Exception: ...


class SteamConfigAdapter(Protocol):
    """Protocol for Steam configuration operations."""

    def grid_dir(self) -> str | None: ...
    def read_shortcuts(self) -> dict: ...
    def write_shortcuts(self, data: dict) -> None: ...
    def set_steam_input_config(self, app_ids: list, mode: str = "default") -> None: ...

    @staticmethod
    def generate_app_id(exe: str, appname: str) -> int: ...

    @staticmethod
    def generate_artwork_id(exe: str, appname: str) -> int: ...
