"""Protocol interfaces for service dependencies.

Services depend on these protocols, not concrete adapter implementations.
This keeps the dependency direction clean: adapters implement protocols,
services consume them.
"""

from __future__ import annotations

from typing import Any, Protocol

from domain.sync_state import SyncState


class SteamConfigAdapter(Protocol):
    """Protocol for Steam configuration operations."""

    def grid_dir(self) -> str | None: ...
    def read_shortcuts(self) -> dict: ...
    def write_shortcuts(self, data: dict) -> None: ...
    def set_steam_input_config(self, app_ids: list, mode: str = "default") -> None: ...


class RommApiProtocol(Protocol):
    """Domain-oriented interface for all RomM server operations.

    Replaces raw HTTP path construction in services with semantic methods.
    Concrete implementations (RommApiBase for v4.6, RommApiV47 for v4.7+)
    handle URL building, version-specific quirks, and response parsing.

    ApiRouter selects the active implementation based on detected server version.
    """

    def set_version(self, version: str) -> None:
        """Set the detected RomM server version.

        Called after heartbeat to select the correct API implementation.
        """
        ...

    def heartbeat(self) -> dict:
        """Check server connectivity and retrieve version info.

        Returns the raw heartbeat response dict from /api/heartbeat.
        """
        ...

    def list_platforms(self) -> list[dict]:
        """Fetch all platforms configured on the RomM server.

        Returns a list of platform dicts from /api/platforms.
        """
        ...

    def list_collections(self) -> list[dict]:
        """Fetch all user-created collections from the RomM server."""
        ...

    def list_virtual_collections(self, collection_type: str) -> list[dict]:
        """Fetch virtual (autogenerated) collections of a given type (e.g., 'franchise')."""
        ...

    def get_current_user(self) -> dict:
        """Fetch the currently authenticated user profile.

        Returns user dict from /api/users/me.
        """
        ...

    def get_rom(self, rom_id: int) -> dict:
        """Fetch a single ROM by ID.

        Returns the ROM dict from /api/roms/{rom_id}.
        """
        ...

    def list_roms(self, platform_id: int, limit: int = 50, offset: int = 0) -> dict:
        """List ROMs for a platform with pagination.

        Returns paginated response {"items": [...], "total": N}
        from /api/roms filtered by platform_ids.
        """
        ...

    def list_roms_updated_after(
        self,
        platform_id: int,
        updated_after: str,
        limit: int = 1,
        offset: int = 0,
    ) -> dict:
        """List ROMs updated after a given timestamp.

        Used for incremental sync to detect changes since last sync.
        Returns paginated response filtered by updated_after parameter.
        """
        ...

    def download_rom_content(
        self,
        rom_id: int,
        filename: str,
        dest: str,
        progress_callback: Any = None,
    ) -> None:
        """Download a ROM file to a local destination.

        Streams /api/roms/{rom_id}/content/{filename} to dest.
        Filename is URL-encoded. Optional progress_callback for tracking.
        """
        ...

    def download_cover(self, cover_url: str, dest: str) -> None:
        """Download a ROM cover image to a local path.

        cover_url is the relative path from the RomM server.
        Spaces in the URL are encoded before downloading.
        """
        ...

    def list_firmware(self) -> list[dict]:
        """Fetch all available firmware/BIOS files from the server.

        Returns a list of firmware dicts from /api/firmware.
        """
        ...

    def get_firmware(self, firmware_id: int) -> dict:
        """Fetch metadata for a single firmware file.

        Returns firmware dict from /api/firmware/{firmware_id}.
        """
        ...

    def download_firmware(self, firmware_id: int, filename: str, dest: str) -> None:
        """Download a firmware/BIOS file to a local path.

        Streams /api/firmware/{firmware_id}/content/{filename} to dest.
        """
        ...

    def list_saves(
        self,
        rom_id: int,
        *,
        device_id: str | None = None,
        slot: str | None = None,
    ) -> list[dict]:
        """List saves for a ROM.

        On v4.7+, pass device_id to populate device_syncs in response,
        and slot to filter by save slot.
        """
        ...

    def upload_save(
        self,
        rom_id: int,
        file_path: str,
        emulator: str,
        save_id: int | None = None,
        *,
        device_id: str | None = None,
        slot: str | None = None,
        overwrite: bool = False,
    ) -> dict:
        """Upload or update a save file.

        On v4.7+, pass device_id for sync tracking, slot for slot assignment,
        and overwrite=True to force-upload over conflicts.
        Raises RommConflictError on 409 when overwrite=False and conflict detected.
        """
        ...

    def download_save_content(
        self,
        save_id: int,
        dest_path: str,
        *,
        device_id: str | None = None,
        optimistic: bool = True,
    ) -> None:
        """Download save content with optional device sync tracking.

        Only available on RomM >= 4.7.0.
        When device_id is set, optimistic=True auto-marks device as synced;
        optimistic=False requires a manual confirm_download() call.
        """
        ...

    def confirm_download(self, save_id: int, device_id: str) -> dict:
        """Manually confirm a save download for device sync tracking.

        Only needed when download_save_content() was called with optimistic=False.
        Only available on RomM >= 4.7.0.
        """
        ...

    def get_save_summary(self, rom_id: int, device_id: str | None = None) -> dict:
        """Fetch grouped save summary for a ROM with slot breakdown.

        Only available on RomM >= 4.7.0.
        Uses /api/saves/summary — returns structured response grouped by slot.
        Pass device_id to include device sync status per save.
        """
        ...

    def download_save(self, save_id: int, dest_path: str) -> None:
        """Download a save file to a local path.

        v4.6: Fetches metadata then downloads via download_path.
        v4.7+: Downloads directly via /api/saves/{save_id}/content.
        """
        ...

    def get_save_metadata(self, save_id: int) -> dict:
        """Fetch metadata for a single save.

        Returns save dict from /api/saves/{save_id}.
        """
        ...

    def get_rom_with_notes(self, rom_id: int) -> dict:
        """Fetch full ROM detail including user notes.

        Used for playtime tracking. Notes are in the all_user_notes field.
        v4.6: /api/roms/{id}/notes returns 500, so uses ROM detail endpoint.
        """
        ...

    def create_note(self, rom_id: int, data: dict) -> dict:
        """Create a note on a ROM.

        Used for playtime tracking. POST /api/roms/{rom_id}/notes.
        """
        ...

    def update_note(self, rom_id: int, note_id: int, data: dict) -> dict:
        """Update an existing note on a ROM.

        PUT /api/roms/{rom_id}/notes/{note_id}.
        """
        ...

    def list_roms_by_collection(self, collection_id: int, limit: int = 50, offset: int = 0) -> dict:
        """List ROMs belonging to a user-created collection with pagination.

        Returns paginated response {"items": [...], "total": N}
        from /api/roms filtered by collection_id.
        Available from RomM 4.7.0.
        """
        ...

    def list_roms_by_virtual_collection(self, virtual_id: str, limit: int = 50, offset: int = 0) -> dict:
        """List ROMs belonging to a virtual (autogenerated) collection with pagination.

        Returns paginated response {"items": [...], "total": N}
        from /api/roms filtered by virtual_collection_id.
        Available from RomM 4.7.0.
        """
        ...

    def delete_server_saves(self, save_ids: list[int]) -> dict:
        """Delete saves from the RomM server by ID.

        Endpoint: POST /api/saves/delete with body {"saves": [id1, id2, ...]}.
        """
        ...

    def supports_device_sync(self) -> bool:
        """Check if the connected RomM server supports device sync (v4.7+).

        Returns True if device registration, slot-based saves, and
        server-side conflict detection are available.
        """
        ...

    def register_device(self, name: str, platform: str, client: str, version: str) -> dict:
        """Register this client as a sync device on the RomM server.

        Only available on RomM >= 4.7.0 (check supports_device_sync() first).
        Returns device dict with id, name, created_at.
        """
        ...


# ---------------------------------------------------------------------------
# Infrastructure callback Protocols
# ---------------------------------------------------------------------------


class StatePersister(Protocol):
    """Persist plugin state to disk (zero-argument callable)."""

    def __call__(self) -> None: ...


class SettingsPersister(Protocol):
    """Persist settings to disk (zero-argument callable)."""

    def __call__(self) -> None: ...


class EventEmitter(Protocol):
    """Emit named events with a data payload to the frontend."""

    async def __call__(self, event: str, /, *args: object) -> None: ...


class DebugLogger(Protocol):
    """Log a debug/trace message string."""

    def __call__(self, msg: str) -> None: ...


class SystemResolver(Protocol):
    """Resolve a RomM platform slug to a RetroDECK system path."""

    def __call__(self, platform_slug: str, platform_fs_slug: str | None = None) -> str: ...


class SavesPathProvider(Protocol):
    """Return the current RetroDECK saves directory path."""

    def __call__(self) -> str: ...


class RomsPathProvider(Protocol):
    """Return the current RetroDECK roms directory path."""

    def __call__(self) -> str: ...


class BiosPathProvider(Protocol):
    """Return the current RetroDECK BIOS directory path."""

    def __call__(self) -> str: ...


class RetroDeckHomeProvider(Protocol):
    """Return the current RetroDECK home directory path."""

    def __call__(self) -> str: ...


class RetroArchSaveSortingProvider(Protocol):
    """Return RetroArch save sorting settings as (sort_by_content, sort_by_core)."""

    def __call__(self) -> tuple[bool, bool]: ...


class CoreResolverFn(Protocol):
    """Resolve the active RetroArch core for a system/game."""

    def __call__(self, system_name: str, rom_filename: str | None = None) -> tuple[str | None, str | None]: ...


class SyncStateRef(Protocol):
    """Return the current sync state value (used by ArtworkService)."""

    def __call__(self) -> SyncState: ...


# ---------------------------------------------------------------------------
# Multi-method cross-service Protocols
# ---------------------------------------------------------------------------


class RetryStrategy(Protocol):
    """HTTP retry wrapper pair consumed by SaveService and PlaytimeService."""

    def is_retryable(self, exc: Exception) -> bool: ...

    def with_retry(self, fn: Any, *args: Any, max_attempts: int = 3, base_delay: int = 1, **kwargs: Any) -> Any: ...


class BiosChecker(Protocol):
    """BIOS status checking consumed by GameDetailService."""

    def check_platform_bios_cached(self, platform_slug: str, rom_filename: str | None = None) -> dict | None: ...

    async def check_platform_bios(self, platform_slug: str, rom_filename: str | None = None) -> dict: ...


class AchievementsReader(Protocol):
    """Achievement data access consumed by GameDetailService."""

    def get_ra_username(self) -> str: ...

    def get_progress_cache_entry(self, rom_id_str: str) -> dict | None: ...


class MetadataExtractor(Protocol):
    """Metadata extraction and cache flushing consumed by LibraryService."""

    def extract_metadata(self, rom: dict) -> dict: ...

    def mark_metadata_dirty(self) -> None: ...

    def flush_metadata_if_dirty(self) -> None: ...


class ArtworkManager(Protocol):
    """Artwork operations consumed by LibraryService."""

    async def download_artwork(
        self,
        all_roms: list[dict],
        emit_progress: Any,
        is_cancelling: Any,
        progress_step: int = 4,
        progress_total_steps: int = 6,
    ) -> dict: ...

    def finalize_cover_path(self, grid: str | None, cover_path: str, app_id: int, rom_id_str: str) -> str: ...

    def remove_artwork_files(self, grid: str, rom_id: str | int, entry: dict) -> None: ...


class SteamGridDbApi(Protocol):
    """SteamGridDB HTTP API — search, artwork fetch, key verification."""

    def request(self, path: str) -> dict | None:
        """Authenticated GET to SGDB API v2. Returns parsed JSON or None if no API key."""
        ...

    def download_image(self, url: str, dest_path: str) -> bool:
        """Download image from URL to dest_path with atomic write. Returns True on success."""
        ...

    def verify_api_key(self, api_key: str) -> dict:
        """Verify an API key against SGDB. Returns parsed JSON response.

        Raises urllib.error.HTTPError on auth failures (401/403).
        """
        ...
